### ISSUE TITLE
some design questions

### ISSUE THREAD

**Issue by duanmengkk** [ferryproxy/ferry#152]
hi, I've also been studying multi-cluster networks recently, I've seen ferry and it seems like it builds a tunnel every time it connects to an svc, why not use tun2SOCKs, like [kt-connect](https://github.com/alibaba/kt-connect), he only seems to build one channel.

**Comment by duanmengkk** [comment]
@wzshiming

**Comment by wzshiming** [comment]
Tun just forwards packets on the L2 network, and socks goes back to using multiple tcp connections, which doesn't save any resources, so I think you might need https://submariner.io/.

**Comment by wzshiming** [comment]
In fact, `kt-connect` uses the ssh protocol as a proxy for connections, which relies on the connection multiplexing capabilities of ssh, and works on a single tcp regardless of the number of connections.

Here's a discussion between me and the author https://github.com/wzshiming/socks5/pull/3

**Comment by wzshiming** [comment]
I was actually going to add tun support to the user terminal, but I haven't had time to do it lately, and was going to use the new tun package I made to replace tun2socks, improving it as I went along. 😄 https://github.com/wzshiming/tun .

**Comment by duanmengkk** [comment]
Thanks for your answer，another question，if svc port number is very long,can ferry or kt-connect satisfy it?
<img width="774" alt="image" src="https://user-images.githubusercontent.com/17697155/212583324-649d46e5-9d0d-45d2-b146-d6dacd78f722.png">

**Comment by wzshiming** [comment]
How long is it? Isn't the maximum only 65535?

**Comment by duanmengkk** [comment]
> How long is it? Isn't the maximum only 65535?

I mean if the number of svc is bigger than 65535, can ferry satisfy it?

**Comment by wzshiming** [comment]
Currently, the number of services imported into a cluster is limited by the number of Pod ports, but the export is not. In the future, it may be possible to support a large number of service imports by supporting multiple Pods sharing import ports.

**Comment by duanmengkk** [comment]
ok，thanks
